/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorAhorro;
import controlador.ControladorBalance;
import controlador.ControladorCategoria;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Ahorro;

/**
 *
 * @author User
 */
public class VentanaAhorro extends javax.swing.JInternalFrame {
    
    private ControladorAhorro controladorAhorro;
    private ControladorBalance controladorBalance;
    private ControladorCategoria controladorCategoria;
    
    private Ahorro ahorro;
    
    private BigDecimal actualizacionAhorro;

    /**
     * Creates new form VentanaAhorro
     *
     * @param controladorAhorro
     * @param controladorBalance
     * @param controladorCategoria
     */
    public VentanaAhorro(ControladorAhorro controladorAhorro, ControladorBalance controladorBalance,
            ControladorCategoria controladorCategoria) {
        initComponents();
        
        this.controladorAhorro = controladorAhorro;
        this.controladorBalance = controladorBalance;
        this.controladorCategoria = controladorCategoria;
        
        actualizacionAhorro = null;
        
    }
    
    public void cargarCodigo() {
        txtCodigo.setText(String.valueOf(controladorAhorro.codigo()));
    }
    
    public void cargarCbxAhorro() {
        cbxCategoria.removeAllItems();
        cbxCategoria.addItem("--Seleccione--");
        controladorCategoria.findByTipo("AHORRO").forEach(cat -> {
            cbxCategoria.addItem(cat.getNombre());
        });
        
    }
    
    public void llenarTbl() {
        var ahorros = controladorAhorro.findAll();
        
        DefaultTableModel modelo = (DefaultTableModel) tblAhorro.getModel();
        modelo.setRowCount(0);
        
        for (Ahorro ah : ahorros) {
            Object[] row = {ah.getId(), ah.getCategoriaFk().getNombre(), ah.getDineroEntrada(), 
                ah.getFecha(), ah.getDescripcion()};
            modelo.addRow(row);
        }
        
        tblAhorro.setModel(modelo);
        
    }
    
    public void cargarFecha() {
        jDateChooser1.setDate(new Date());
    }
    
    public void limpiar() {
        cargarCbxAhorro();
        cargarCodigo();
        llenarTbl();
        cargarFecha();
        
        txtAreaDescripcion.setText("");
        cbxCategoria.setSelectedItem(0);
        txtDinero.setText("");
        
        btnCrear.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDinero = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cbxCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAhorro = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Código:");

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setText("Categoria:");

        jLabel3.setText("Dinero:");

        btnCrear.setBackground(new java.awt.Color(51, 51, 255));
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(102, 102, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 102, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha:");

        jLabel5.setText("Descripción:");

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setLineWrap(true);
        txtAreaDescripcion.setRows(5);
        txtAreaDescripcion.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAreaDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo)
                            .addComponent(txtDinero)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnCrear)
                        .addGap(38, 38, 38)
                        .addComponent(btnActualizar)
                        .addGap(42, 42, 42)
                        .addComponent(btnEliminar)
                        .addGap(47, 47, 47)
                        .addComponent(btnCancelar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tblAhorro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria", "Entrada", "Fecha", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAhorro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAhorroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAhorro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:

        int codigo = Integer.valueOf(txtCodigo.getText());
        String categoria = (String) cbxCategoria.getSelectedItem();
        String descripcion = txtAreaDescripcion.getText();
        String dineroAhorroString = txtDinero.getText();
        Date fecha = jDateChooser1.getDate();
        
        if (dineroAhorroString.contains(",")) {
            dineroAhorroString = dineroAhorroString.replaceAll(",", ".");
        }
        //dineroGastadoString = String.format(".2f", dineroGastadoString);
        double dineroAhorrado = Double.valueOf(dineroAhorroString);
        
        if (categoria.equals("--Seleccione--") || dineroAhorroString.isBlank()) {
            JOptionPane.showMessageDialog(this, "Faltan datos", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            BigDecimal ahorroDinero = BigDecimal.valueOf(dineroAhorrado);
            var category = controladorCategoria.findByNombre(categoria);
            
            Ahorro ah = new Ahorro(descripcion, category, fecha,
                    Integer.valueOf(txtCodigo.getText()), ahorroDinero);
            
            if (controladorAhorro.create(ah) && controladorBalance.ahorro(ahorroDinero)) {
                JOptionPane.showMessageDialog(this, "Creado con exito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Error", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
            
        }

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:

        String categoria = (String) cbxCategoria.getSelectedItem();
        String descripcion = txtAreaDescripcion.getText();
        String dineroAhorroString = txtDinero.getText();
        Date fecha = jDateChooser1.getDate();
        
        if (dineroAhorroString.contains(",")) {
            dineroAhorroString = dineroAhorroString.replaceAll(",", ".");
        }
        //dineroGastadoString = String.format(".2f", dineroGastadoString);
        double dineroAhorrado = Double.valueOf(dineroAhorroString);
        
        if (categoria.equals("--Seleccione--") || dineroAhorroString.isBlank()) {
            JOptionPane.showMessageDialog(this, "Faltan datos", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            BigDecimal ahorroDinero = BigDecimal.valueOf(dineroAhorrado);
            
            var category = controladorCategoria.findByNombre(categoria);
            
            ahorro.setFecha(fecha);
            ahorro.setCategoriaFk(category);
            ahorro.setDineroEntrada(ahorroDinero);
            ahorro.setDescripcion(descripcion);
            
            if (controladorAhorro.update(ahorro) && controladorBalance.gasto(actualizacionAhorro)
                    && controladorBalance.ahorro(ahorroDinero)) {
                JOptionPane.showMessageDialog(this, "Actualizado con exito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Error", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
            
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        int codigo = Integer.valueOf(txtCodigo.getText());
        
        ahorro = controladorAhorro.read(codigo);
        
        if (controladorAhorro.delete(ahorro) && controladorBalance.gasto(ahorro.getDineroEntrada())) {
            JOptionPane.showMessageDialog(this, "Eliminado con exito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "Error", "Aviso", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblAhorroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAhorroMouseClicked
        // TODO add your handling code here:

        int fila = tblAhorro.getSelectedRow();
        
        int codigo = (int) tblAhorro.getValueAt(fila, 0);
        
        ahorro = controladorAhorro.read(codigo);
        
        txtCodigo.setText(String.valueOf(ahorro.getId()));
        cbxCategoria.setSelectedItem(ahorro.getCategoriaFk().getNombre());
        txtDinero.setText(ahorro.getDineroEntrada().toString());
        jDateChooser1.setDate(ahorro.getFecha());
        txtAreaDescripcion.setText(ahorro.getDescripcion());
        
        actualizacionAhorro = ahorro.getDineroEntrada();
        
        btnCrear.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);

    }//GEN-LAST:event_tblAhorroMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAhorro;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDinero;
    // End of variables declaration//GEN-END:variables
}
