/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorAhorro;
import controlador.ControladorBalance;
import controlador.ControladorGastos;
import java.awt.HeadlessException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VentanaBalance extends javax.swing.JInternalFrame {
    
    private ControladorGastos controladorGastos;
    private ControladorAhorro controladorAhorro;
    private ControladorBalance controladorBalance;
    
    private VentanaMostrarBalance ventanaMostrarBalance;

    /**
     * Creates new form VentanaBalance
     *
     * @param controladorGastos
     * @param controladorAhorro
     * @param controladorBalance
     * @param ventanaBalance
     */
    public VentanaBalance(ControladorGastos controladorGastos, ControladorAhorro controladorAhorro,
            ControladorBalance controladorBalance, VentanaMostrarBalance ventanaMostrarBalance) {
        initComponents();
        
        this.controladorAhorro = controladorAhorro;
        this.controladorGastos = controladorGastos;
        this.controladorBalance = controladorBalance;
        this.ventanaMostrarBalance = ventanaMostrarBalance;
        
    }
    
    public void cargarGastos() {
        txtGastos.setText(controladorGastos.calcularTotal().toString());
    }
    
    public void cargarAhorros() {
        txtAhorros.setText(controladorAhorro.calcularTotal().toString());
    }
    
    public void cargarBalance() {
        txtBalance.setText(controladorBalance.findAll().get(controladorBalance.findAll().size() - 1).getDinero().toString());
    }
    
    public void limpiar() {
        cargarAhorros();
        cargarGastos();
        cargarBalance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGastos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAhorros = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        btnBalanceAnio = new javax.swing.JButton();
        btnBalanceMes = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Total gastos:");

        txtGastos.setEditable(false);
        txtGastos.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setText("Total ahorros:");

        txtAhorros.setEditable(false);
        txtAhorros.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setText("Balance:");

        txtBalance.setEditable(false);
        txtBalance.setBackground(new java.awt.Color(102, 102, 102));

        btnBalanceAnio.setBackground(new java.awt.Color(70, 167, 147));
        btnBalanceAnio.setText("Balance por año");
        btnBalanceAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceAnioActionPerformed(evt);
            }
        });

        btnBalanceMes.setBackground(java.awt.SystemColor.textHighlight);
        btnBalanceMes.setText("Balance por mes");
        btnBalanceMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBalanceAnio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBalanceMes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(25, 25, 25)
                                .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBalanceAnio)
                    .addComponent(btnBalanceMes))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        limpiar();

    }//GEN-LAST:event_formInternalFrameOpened

    private void btnBalanceAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceAnioActionPerformed
        // TODO add your handling code here:

        try {
            int anio;
            do {
                anio = Integer.valueOf(JOptionPane.showInputDialog(this, "¿Qué año?", "Selección año", JOptionPane.QUESTION_MESSAGE));
            } while (anio < 2021 || anio > (new Date().getYear() + 1900));
            
            ventanaMostrarBalance.setAnio(anio);
            ventanaMostrarBalance.llenarPorAnio();
            ventanaMostrarBalance.setVisible(true);
            
        } catch (HeadlessException | NumberFormatException e) {
            
        }

    }//GEN-LAST:event_btnBalanceAnioActionPerformed

    private void btnBalanceMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceMesActionPerformed
        // TODO add your handling code here:

        try {
            int mes;
            do {
                mes = Integer.valueOf(JOptionPane.showInputDialog(this, "Número del mes", "Selección mes", JOptionPane.QUESTION_MESSAGE));
            } while (mes < 1 || mes > 12);
            
            mes -= 1;
            
            ventanaMostrarBalance.setNumeroMes(mes);
            ventanaMostrarBalance.llenarPorMes();
            ventanaMostrarBalance.setVisible(true);
            
        } catch (HeadlessException | NumberFormatException e) {
        }
        

    }//GEN-LAST:event_btnBalanceMesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalanceAnio;
    private javax.swing.JButton btnBalanceMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAhorros;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtGastos;
    // End of variables declaration//GEN-END:variables
}
