/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorAhorro;
import controlador.ControladorGastos;
import java.math.RoundingMode;
import javax.swing.table.DefaultTableModel;
import modelo.Ahorro;
import modelo.Gasto;

/**
 *
 * @author User
 */
public class VentanaMostrarBalance extends javax.swing.JInternalFrame {

    private ControladorAhorro controladorAhorro;
    private ControladorGastos controladorGastos;

    private int numeroMes;
    private int anio;

    /**
     * Creates new form VentanaMostrarBalance
     *
     * @param controladorAhorro
     * @param controladorGastos
     */
    public VentanaMostrarBalance(ControladorAhorro controladorAhorro,
            ControladorGastos controladorGastos) {
        initComponents();

        this.controladorAhorro = controladorAhorro;
        this.controladorGastos = controladorGastos;

    }

    public void limpiar() {
        DefaultTableModel modeloGastos = (DefaultTableModel) tblGastos.getModel();
        modeloGastos.setRowCount(0);

        DefaultTableModel modeloAhorros = (DefaultTableModel) tblAhorro.getModel();
        modeloAhorros.setRowCount(0);
    }

    public void llenarPorMes() {

        var listaGastos = controladorGastos.findByMes(numeroMes);

        DefaultTableModel modeloGastos = (DefaultTableModel) tblGastos.getModel();
        modeloGastos.setRowCount(0);

        for (Gasto gas : listaGastos) {
            Object[] row = {gas.getId(), gas.getCategoriaFk().getNombre(), gas.getDineroGastado().toString(),
                gas.getFecha().toString(), gas.getDescripcion()};
            modeloGastos.addRow(row);
        }

        tblGastos.setModel(modeloGastos);
        txtTotalGastos.setText(controladorGastos.calcularTotalPorMes(numeroMes).toString());

        var listaAhorro = controladorAhorro.findByMes(numeroMes);

        DefaultTableModel modeloAhorro = (DefaultTableModel) tblAhorro.getModel();
        modeloAhorro.setRowCount(0);

        for (Ahorro ah : listaAhorro) {
            Object[] row = {ah.getId(), ah.getCategoriaFk().getNombre(), ah.getDineroEntrada().toString(),
                ah.getFecha().toString(), ah.getDescripcion()};
            modeloAhorro.addRow(row);
        }

        tblAhorro.setModel(modeloAhorro);
        txtTotalAhorro.setText(controladorAhorro.calcularTotalPorMes(numeroMes).toString());

        txtBalance.setText((controladorAhorro.calcularTotalPorMes(numeroMes).subtract(controladorGastos.calcularTotalPorMes(numeroMes))).setScale(2, RoundingMode.HALF_UP).toString());

    }

    public void llenarPorAnio() {

        var listaGastos = controladorGastos.findByAnio(anio);

        DefaultTableModel modeloGastos = (DefaultTableModel) tblGastos.getModel();
        modeloGastos.setRowCount(0);

        for (Gasto gas : listaGastos) {
            Object[] row = {gas.getId(), gas.getCategoriaFk().getNombre(), gas.getDineroGastado().toString(),
                gas.getFecha().toString(), gas.getDescripcion()};
            modeloGastos.addRow(row);
        }

        tblGastos.setModel(modeloGastos);
        txtTotalGastos.setText(controladorGastos.calcularTotalPorAnio(anio).toString());

        var listaAhorro = controladorAhorro.findByAnio(anio);

        DefaultTableModel modeloAhorro = (DefaultTableModel) tblAhorro.getModel();
        modeloAhorro.setRowCount(0);

        for (Ahorro ah : listaAhorro) {
            Object[] row = {ah.getId(), ah.getCategoriaFk().getNombre(), ah.getDineroEntrada().toString(),
                ah.getFecha().toString(), ah.getDescripcion()};
            modeloAhorro.addRow(row);
        }

        tblAhorro.setModel(modeloAhorro);
        txtTotalAhorro.setText(controladorAhorro.calcularTotalPorAnio(anio).toString());

        txtBalance.setText((controladorAhorro.calcularTotalPorAnio(anio).subtract(controladorGastos.calcularTotalPorAnio(anio))).setScale(2, RoundingMode.HALF_UP).toString());

    }

    public int getNumeroMes() {
        return numeroMes;
    }

    public void setNumeroMes(int numeroMes) {
        this.numeroMes = numeroMes;
    }

    public int getAnio() {
        return anio;
    }

    public void setAnio(int anio) {
        this.anio = anio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGastos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAhorro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalGastos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotalAhorro = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria", "Gasto", "Fecha", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGastos);

        tblAhorro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria", "Ahorro", "Fecha", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAhorro);

        jLabel1.setText("Gastos:");

        jLabel2.setText("Ahorros:");

        txtTotalGastos.setEditable(false);
        txtTotalGastos.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setText("Balance:");

        txtTotalAhorro.setEditable(false);
        txtTotalAhorro.setBackground(new java.awt.Color(102, 102, 102));

        txtBalance.setEditable(false);
        txtBalance.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtTotalGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtTotalAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        limpiar();


    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAhorro;
    private javax.swing.JTable tblGastos;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtTotalAhorro;
    private javax.swing.JTextField txtTotalGastos;
    // End of variables declaration//GEN-END:variables
}
