/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorAhorro;
import controlador.ControladorBalance;
import controlador.ControladorCategoria;
import controlador.ControladorGastos;

/**
 *
 * @author User
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControladorCategoria controladorCategoria;
    private ControladorGastos controladorGastos;
    private ControladorAhorro controladorAhorro;
    private ControladorBalance controladorBalance;

    private VentanaCategoria ventanaCategoria;
    private VentanaGastos ventanaGastos;
    private VentanaVistaGastos ventanaVistaGastos;
    private VentanaAhorro ventanaAhorro;
    private VentanaBalance ventanaBalance;
    private VentanaMostrarBalance ventanaMostrarBalance;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        controladorCategoria = new ControladorCategoria();
        controladorGastos = new ControladorGastos();
        controladorAhorro = new ControladorAhorro();
        controladorBalance = new ControladorBalance();

        ventanaMostrarBalance = new VentanaMostrarBalance(controladorAhorro, controladorGastos);
        ventanaCategoria = new VentanaCategoria(controladorCategoria);
        ventanaGastos = new VentanaGastos(controladorCategoria, controladorGastos, controladorBalance);
        ventanaVistaGastos = new VentanaVistaGastos(controladorCategoria, controladorGastos);
        ventanaAhorro = new VentanaAhorro(controladorAhorro, controladorBalance, controladorCategoria);
        ventanaBalance = new VentanaBalance(controladorGastos, controladorAhorro, controladorBalance,
                ventanaMostrarBalance);

        desktopPane.add(ventanaCategoria);
        desktopPane.add(ventanaGastos);
        desktopPane.add(ventanaVistaGastos);
        desktopPane.add(ventanaAhorro);
        desktopPane.add(ventanaBalance);
        desktopPane.add(ventanaMostrarBalance);

        this.setExtendedState(VentanaPrincipal.MAXIMIZED_BOTH);
    }

    public void cerrarVentanas() {
        ventanaCategoria.hide();
        ventanaGastos.hide();
        ventanaVistaGastos.hide();
        ventanaAhorro.hide();
        ventanaBalance.hide();
        ventanaMostrarBalance.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        inicioMenu = new javax.swing.JMenu();
        categoriaMenuItem = new javax.swing.JMenuItem();
        gastoMenuItem = new javax.swing.JMenuItem();
        ahorroMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        vistaGastosMenuItem = new javax.swing.JMenuItem();
        balanceMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gastos Personales");

        inicioMenu.setMnemonic('f');
        inicioMenu.setText("Inicio");

        categoriaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        categoriaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/categoryPequeño.jpg"))); // NOI18N
        categoriaMenuItem.setMnemonic('o');
        categoriaMenuItem.setText("Categoria");
        categoriaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(categoriaMenuItem);

        gastoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        gastoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/speee.jpg"))); // NOI18N
        gastoMenuItem.setMnemonic('a');
        gastoMenuItem.setText("Gasto");
        gastoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastoMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(gastoMenuItem);

        ahorroMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ahorroMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/saving_1.jpg"))); // NOI18N
        ahorroMenuItem.setText("Ahorro");
        ahorroMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ahorroMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(ahorroMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exit.jpg"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(exitMenuItem);

        menuBar.add(inicioMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Gestion");

        vistaGastosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        vistaGastosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/b2_1.jpg"))); // NOI18N
        vistaGastosMenuItem.setMnemonic('c');
        vistaGastosMenuItem.setText("Vista Gastos");
        vistaGastosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vistaGastosMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(vistaGastosMenuItem);

        balanceMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        balanceMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/balance_1.jpg"))); // NOI18N
        balanceMenuItem.setText("Balance");
        balanceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(balanceMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void categoriaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        ventanaCategoria.setVisible(true);
    }//GEN-LAST:event_categoriaMenuItemActionPerformed

    private void gastoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastoMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        ventanaGastos.setVisible(true);

    }//GEN-LAST:event_gastoMenuItemActionPerformed

    private void vistaGastosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaGastosMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        ventanaVistaGastos.setVisible(true);
    }//GEN-LAST:event_vistaGastosMenuItemActionPerformed

    private void ahorroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ahorroMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        ventanaAhorro.setVisible(true);
    }//GEN-LAST:event_ahorroMenuItemActionPerformed

    private void balanceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceMenuItemActionPerformed
        // TODO add your handling code here:
        cerrarVentanas();
        ventanaBalance.setVisible(true);
    }//GEN-LAST:event_balanceMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ahorroMenuItem;
    private javax.swing.JMenuItem balanceMenuItem;
    private javax.swing.JMenuItem categoriaMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem gastoMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu inicioMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem vistaGastosMenuItem;
    // End of variables declaration//GEN-END:variables

}
